export default [
  {
    id: 0,
    text:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sit amet eros quis quam suscipit sollicitudin. Aenean commodo volutpat mauris, eget faucibus mauris commodo eget. Phasellus et efficitur enim, non placerat sem. In neque dolor, maximus non auctor bibendum, lobortis a neque. Nam dapibus pellentesque venenatis. Fusce aliquet arcu a tristique lacinia. Aliquam erat volutpat. Sed sollicitudin blandit maximus. Aenean nisl lacus, ultricies quis porttitor ullamcorper, tempus et risus. Nullam ultricies purus vel felis viverra placerat. Duis hendrerit arcu lectus. Aliquam at lacus libero. Aliquam non lorem tincidunt, rutrum lacus at, aliquet dolor. Curabitur lorem metus, dictum non porta lacinia, consequat vel lacus. Vestibulum facilisis sodales mauris, tincidunt efficitur sapien efficitur et. Nam finibus metus sit amet leo iaculis accumsan. Integer nulla purus, mollis nec malesuada id, luctus sed ante. Nulla facilisi. Donec nec placerat magna. In pretium cursus augue, at sagittis ante sollicitudin non. Nam ullamcorper, tellus quis condimentum auctor, metus tellus laoreet mauris, nec facilisis nunc purus nec nulla. Morbi et cursus purus. Integer at enim vitae urna interdum ultricies. Nulla et mi mattis, molestie sapien et, porttitor massa. Maecenas quis semper lorem, eget dignissim erat. Aenean condimentum lectus et nunc sagittis, at consectetur ex eleifend. Cras sed dui vitae velit blandit facilisis et et nibh. Nullam pulvinar, quam ullamcorper gravida viverra, neque nibh consectetur purus, ornare imperdiet ex lectus ut dolor. Etiam tincidunt magna lectus, vitae fringilla velit sagittis sit amet. Duis egestas sollicitudin dui, sed viverra leo tincidunt non. Ut at nibh quis diam rutrum ultrices. Donec sit amet sollicitudin nisi. Donec bibendum ornare tortor. Maecenas ut vulputate nisi. Mauris ut lorem quam."
  },
  {
    id: 1,
    text:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sit amet eros quis quam suscipit sollicitudin. Aenean commodo volutpat mauris, eget faucibus mauris commodo eget. Phasellus et efficitur enim, non placerat sem. In neque dolor, maximus non auctor bibendum, lobortis a neque. Nam dapibus pellentesque venenatis. Fusce aliquet arcu a tristique lacinia. Aliquam erat volutpat. Sed sollicitudin blandit maximus. Aenean nisl lacus, ultricies quis porttitor ullamcorper, tempus et risus. Nullam ultricies purus vel felis viverra placerat. Duis hendrerit arcu lectus. Aliquam at lacus libero. Aliquam non lorem tincidunt, rutrum lacus at, aliquet dolor. Curabitur lorem metus, dictum non porta lacinia, consequat vel lacus. Vestibulum facilisis sodales mauris, tincidunt efficitur sapien efficitur et. Nam finibus metus sit amet leo iaculis accumsan. Integer nulla purus, mollis nec malesuada id, luctus sed ante. Nulla facilisi. Donec nec placerat magna. In pretium cursus augue, at sagittis ante sollicitudin non. Nam ullamcorper, tellus quis condimentum auctor, metus tellus laoreet mauris, nec facilisis nunc purus nec nulla. Morbi et cursus purus. Integer at enim vitae urna interdum ultricies. Nulla et mi mattis, molestie sapien et, porttitor massa. Maecenas quis semper lorem, eget dignissim erat. Aenean condimentum lectus et nunc sagittis, at consectetur ex eleifend. Cras sed dui vitae velit blandit facilisis et et nibh. Nullam pulvinar, quam ullamcorper gravida viverra, neque nibh consectetur purus, ornare imperdiet ex lectus ut dolor. Etiam tincidunt magna lectus, vitae fringilla velit sagittis sit amet. Duis egestas sollicitudin dui, sed viverra leo tincidunt non. Ut at nibh quis diam rutrum ultrices. Donec sit amet sollicitudin nisi. Donec bibendum ornare tortor. Maecenas ut vulputate nisi. Mauris ut lorem quam."
  },
  {
    id: 2,
    text:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sit amet eros quis quam suscipit sollicitudin. Aenean commodo volutpat mauris, eget faucibus mauris commodo eget. Phasellus et efficitur enim, non placerat sem. In neque dolor, maximus non auctor bibendum, lobortis a neque. Nam dapibus pellentesque venenatis. Fusce aliquet arcu a tristique lacinia. Aliquam erat volutpat. Sed sollicitudin blandit maximus. Aenean nisl lacus, ultricies quis porttitor ullamcorper, tempus et risus. Nullam ultricies purus vel felis viverra placerat. Duis hendrerit arcu lectus. Aliquam at lacus libero. Aliquam non lorem tincidunt, rutrum lacus at, aliquet dolor. Curabitur lorem metus, dictum non porta lacinia, consequat vel lacus. Vestibulum facilisis sodales mauris, tincidunt efficitur sapien efficitur et. Nam finibus metus sit amet leo iaculis accumsan. Integer nulla purus, mollis nec malesuada id, luctus sed ante. Nulla facilisi. Donec nec placerat magna. In pretium cursus augue, at sagittis ante sollicitudin non. Nam ullamcorper, tellus quis condimentum auctor, metus tellus laoreet mauris, nec facilisis nunc purus nec nulla. Morbi et cursus purus. Integer at enim vitae urna interdum ultricies. Nulla et mi mattis, molestie sapien et, porttitor massa. Maecenas quis semper lorem, eget dignissim erat. Aenean condimentum lectus et nunc sagittis, at consectetur ex eleifend. Cras sed dui vitae velit blandit facilisis et et nibh. Nullam pulvinar, quam ullamcorper gravida viverra, neque nibh consectetur purus, ornare imperdiet ex lectus ut dolor. Etiam tincidunt magna lectus, vitae fringilla velit sagittis sit amet. Duis egestas sollicitudin dui, sed viverra leo tincidunt non. Ut at nibh quis diam rutrum ultrices. Donec sit amet sollicitudin nisi. Donec bibendum ornare tortor. Maecenas ut vulputate nisi. Mauris ut lorem quam."
  },
  {
    id: 3,
    text:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sit amet eros quis quam suscipit sollicitudin. Aenean commodo volutpat mauris, eget faucibus mauris commodo eget. Phasellus et efficitur enim, non placerat sem. In neque dolor, maximus non auctor bibendum, lobortis a neque. Nam dapibus pellentesque venenatis. Fusce aliquet arcu a tristique lacinia. Aliquam erat volutpat. Sed sollicitudin blandit maximus. Aenean nisl lacus, ultricies quis porttitor ullamcorper, tempus et risus. Nullam ultricies purus vel felis viverra placerat. Duis hendrerit arcu lectus. Aliquam at lacus libero. Aliquam non lorem tincidunt, rutrum lacus at, aliquet dolor. Curabitur lorem metus, dictum non porta lacinia, consequat vel lacus. Vestibulum facilisis sodales mauris, tincidunt efficitur sapien efficitur et. Nam finibus metus sit amet leo iaculis accumsan. Integer nulla purus, mollis nec malesuada id, luctus sed ante. Nulla facilisi. Donec nec placerat magna. In pretium cursus augue, at sagittis ante sollicitudin non. Nam ullamcorper, tellus quis condimentum auctor, metus tellus laoreet mauris, nec facilisis nunc purus nec nulla. Morbi et cursus purus. Integer at enim vitae urna interdum ultricies. Nulla et mi mattis, molestie sapien et, porttitor massa. Maecenas quis semper lorem, eget dignissim erat. Aenean condimentum lectus et nunc sagittis, at consectetur ex eleifend. Cras sed dui vitae velit blandit facilisis et et nibh. Nullam pulvinar, quam ullamcorper gravida viverra, neque nibh consectetur purus, ornare imperdiet ex lectus ut dolor. Etiam tincidunt magna lectus, vitae fringilla velit sagittis sit amet. Duis egestas sollicitudin dui, sed viverra leo tincidunt non. Ut at nibh quis diam rutrum ultrices. Donec sit amet sollicitudin nisi. Donec bibendum ornare tortor. Maecenas ut vulputate nisi. Mauris ut lorem quam."
  }
];
